// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdwmlenkxtgtoauortkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkd21sZW5reHRndG9hdW9ydGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDQ3NzQsImV4cCI6MjA2MTIyMDc3NH0.D7fA39BhdttDLG_ut3BzagK2yrx1MNl0-xiXgzegYrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);