[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_charge = "ChrgsEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnrr"
sol_charge_tokens = "TokenEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnVV"
sol_charge_staking = "StakeEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnXX"

[programs.devnet]
sol_charge = "ChrgsEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnrr"
sol_charge_tokens = "TokenEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnVV"
sol_charge_staking = "StakeEjMTwJy1VvDsR6z6G2xNbQwEzK5HyE8mRfPUTnXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
verify = "anchor verify" 